### ISSUE TITLE
instance_types.get() doesn't work anymore

### ISSUE THREAD

**Issue by Xirider** [DataCrunch-io/datacrunch-python#1]
Since yesterday when i try to get the instance types:

` instance_types = datacrunch.instance_types.get()`

i get the following error:

`---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-18-bf7bb2e8b41f> in <module>
----> 1 instance_types = datacrunch.instance_types.get()

~\anaconda3\lib\site-packages\datacrunch\instance_types\instance_types.py in get(self)
    129         """
    130         instance_types = self._http_client.get(INSTANCE_TYPES_ENDPOINT).json()
--> 131         instance_type_objects = list(map(lambda instance_type: InstanceType(
    132             id=instance_type['id'],
    133             instance_type=instance_type['instance_type'],

~\anaconda3\lib\site-packages\datacrunch\instance_types\instance_types.py in <lambda>(instance_type)
    137             gpu=instance_type['gpu'],
    138             memory=instance_type['memory'],
--> 139             storage=instance_type['storage']
    140         ), instance_types))
    141 

KeyError: 'storage'`

**Comment by tamirse** [comment]
Hey @Xirider, thanks for opening the issue.

We will start working on it ASAP, and also include support for Storage Volumes, RTX A6000 instance & CPU instances.
The API is currently in beta stage so such issues were possible.
After the fix, it should go into a stable state.

**Comment by Xirider** [comment]
Thanks :)

**Comment by tamirse** [comment]
Hey @Xirider 

`instance_types.get()` has been fixed and should work now.

Storage Volumes, RTX A6000 instance & CPU instances are still being worked on.

Let me know if you still encounter issues.
Cheers
