### ISSUE TITLE
Cannot create spot instances using the API

### ISSUE THREAD

**Issue by jpc** [DataCrunch-io/datacrunch-python#11]
Hi,

I am trying to create spot instances and despite `is_spot` being documented actually passing `True` breaks the API for me. Here is my code:
```
instance = datacrunch.instances.create(instance_type='1A100.22V',
                                      image='fastai',
                                      ssh_key_ids=ssh_keys,
                                      hostname='whisper',
                                      description='Whisper machine',
                                      is_spot=True)
```

With `is_spot=True` I always get:
```
datacrunch.exceptions.APIException: error code: invalid_request
```

When I change this to `is_spot=False` the same API calls succeed which made me believe there is something wrong with the API for spot instances.

**Comment by jpc** [comment]
I've upgraded from `1.0.10` to the recently released `1.1.0` but the issue persisted.

**Comment by tamirse** [comment]
Hey Jakub, thanks for reporting.
We have fixed the issue. It was a bug with the public API.

**Comment by jpc** [comment]
Works perfectly know, thanks! :)
