### ISSUE TITLE
Unable to delete an instance

### ISSUE THREAD

**Issue by mark-selyaeff** [DataCrunch-io/datacrunch-python#14]
After shutting down and hibernating an instance, I am unable to call delete command. The instance is listed as `discontinued` and is no longer visible by calling `.instances.get()`:
```
>>> datacrunch.instances.get()
Out[26]: []
>>> print_instance_info(datacrunch.instances.get_by_id(instance_id))
Out[27]: {'id': '37f...fd2', 'status': 'discontinued'}
```
Calling delete on that instance raises APIException:
```
datacrunch.exceptions.APIException: error code: forbidden_action
message: Can't discontinue a discontinued instance
```
How to properly delete an instance to stop being charged for it? At least from my observations shutdown & hibernate commands are enough to stop balance charging, but I am concerned by the fact that I haven't managed to delete an instance without API error.

**Comment by tamirse** [comment]
Hi Mark,
Hibernation works by actually deleting your instance but keeping the volumes that were attached to the instance originally.
that means the instance is deleted, but the volumes are still being charged for.

If you would like to completely delete both the instance and volumes you need to specify them explicitly.

> When deleting an instance, you can specify which of it's attached volumes will be deleted by providing volume_ids array. Any attached volumes that are not specified in the array would be detached. Note: If not providing a volume_ids array, only the OS volume will be deleted and the rest detached.

An example is found here: https://github.com/DataCrunch-io/datacrunch-python/blob/master/examples/instances_and_volumes.py
