### ISSUE TITLE
Spot price

### ISSUE THREAD

**Issue by zoq** [DataCrunch-io/datacrunch-python#20]
Currently:

https://github.com/DataCrunch-io/datacrunch-python/blob/29c25603b73b6748513f5fa162ed27c1cda60f05/datacrunch/instance_types/instance_types.py#L68

returns the price per hour for the on-demand price, are there any plans to return the spot price as well?

**Comment by tamirse** [comment]
Thanks for pointing this out. 
I have added the spot price and made a new release v1.6.1
