### ISSUE TITLE
How to use coupon code on creating instance

### ISSUE THREAD

**Issue by huynguyen-faty** [DataCrunch-io/datacrunch-python#8]
Hi team. Currently, we can apply discount coupon on the web UI but for the api & sdk look like we dont have it. So how can we apply the coupon via api/sdk for now, should we wait for the update or do we have any workaround? Thank you.

**Comment by tamirse** [comment]
Hi!
We've added support for applying a coupon when creating a new instance, on version 1.0.10 of the SDK.
Could you check that now?
